#!/bin/sh

#######################################
#  _                                  #
# | |__  ___ _ ____      ___ __ ___   #
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \  #
# | |_) \__ \ |_) \ V  V /| | | | | | #
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_| #
#           |_|                       #
#######################################

# Kill already running processes
killall -q sxhkd

# Startups
# compton &
feh --no-fehbg --bg-fill $HOME/Pictures/Wallpaper/Default/nord/wp2.jpg
# Use normal sxhkd config if on planck keyboard
# Else use config for staggered regular keyboards
if xinput --list --name-only | grep -q Planck; then
    sxhkd &
else
    sxhkd -c $XDG_CONFIG_HOME/sxhkd/sxhkdrc_staggered &
    setxkbmap -layout us -option ctrl:nocaps
    setxkbmap -layout us -option ctrl:swap_lwin_lctl
fi
$HOME/.config/polybar/launch.sh

# Define desktop/workspaces for each monitor based on computer used
if [[ $(hostname) == 'thinkpad' ]]; then
    bspc monitor eDP1 -d I II III IV
    xinput --disable "Synaptics TM3289-021"
elif [[ $(hostname) == 'desktop' ]]; then
    bspc monitor DP-2 -d I II III IV
    # bspc monitor HDMI-0 -d V VI VII VIII
fi

# Window config
# bspc config focus_follows_pointer true
bspc config border_width         2
bspc config window_gap           10

# Layout config
# bspc config automatic_scheme automatic
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Colorscheme
bspc config focused_border_color   "#5e81ac"
bspc config normal_border_color    "#3b4252"
bspc config presel_feedback_color  "#3b4252"

# Rules
bspc rule -a Chromium desktop='^2'
bspc rule -a Signal desktop='^3'
bspc rule -a Screenkey manage=off
bspc rule -a KeePassXC state=floating follow=on
bspc rule -a Zathura state=tiled
bspc rule -a matplotlib state=floating
