#! /bin/sh

#######################################
#  _                                  #
# | |__  ___ _ ____      ___ __ ___   #
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \  #
# | |_) \__ \ |_) \ V  V /| | | | | | #
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_| #
#           |_|                       #
#######################################

# Kill already running processes
killall -q sxhkd
killall -q feh

# Startups
# compton &
sxhkd &
feh --bg-fill $HOME/Pictures/wp.jpg
$HOME/.config/polybar/launch.sh

# Define desktop/workspaces for each monitor
if [[ $(hostname) == 'thinkpad' ]]; then
    bspc monitor eDP1 -d I II III IV
elif [[ $(hostname) == 'desktop' ]]; then
    bspc monitor DP-2 -d I II III IV
    # bspc monitor HDMI-0 -d V VI VII VIII
fi


# Window config
# bspc config focus_follows_pointer true
bspc config border_width         2
bspc config window_gap          10

# Layout config
# bspc config automatic_scheme automatic
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Colorscheme
bspc config focused_border_color   "#29b8db"
bspc config presel_feedback_color  "#3B4252"

# Rules
# bspc rule -a Chromium desktop='^5'
bspc rule -a Screenkey manage=off
bspc rule -a KeePassXC state=floating follow=on
bspc rule -a Zathura state=tiled
bspc rule -a Matplotlib state=floating
