# Inserts a blank line between shell prompts
add_newline = false

[character]
success_symbol = "[➜](bold green)"

[cmd_duration]
disabled = true

[git_branch]
style = "bold red"
format = "[git:\\([$branch](bold red)\\)](bold blue) "
#format = "[$symbol](bold blue)[$branch]($style) "

[line_break]
disabled = true

[package]
disabled = true

[rust]
disabled = true
